"""
Game History Keys - Centralized Key Management

Purpose:
    This is the ONLY place where R2 object keys are generated.
    All key patterns are defined here to prevent key fragmentation.

Why this file is critical:
    Keys are the "schema" of object storage. If different parts of the
    system generate keys differently, you get:
    - Lost objects
    - Duplicate objects
    - Inability to migrate
    - Debugging nightmares

Key Principles:
    1. All keys are generated by functions in this file
    2. No other file should ever construct a key string
    3. Keys use simple, predictable patterns
    4. Keys do NOT encode user_id (visibility is managed by index)

Current Key Patterns:
    games/{game_id}.pgn          - Game PGN content
    analysis/{game_id}.json      - Engine analysis results
    training/{game_id}.json      - Training data (future)
"""


def game_pgn(game_id: str) -> str:
    """
    Generate key for game PGN file.

    Args:
        game_id: Unique game identifier

    Returns:
        R2 object key (e.g., "games/abc123.pgn")

    Example:
        >>> game_pgn("8f2a9c")
        'games/8f2a9c.pgn'
    """
    return f"games/{game_id}.pgn"


def game_analysis(game_id: str) -> str:
    """
    Generate key for game analysis JSON.

    Args:
        game_id: Unique game identifier

    Returns:
        R2 object key (e.g., "analysis/abc123.json")

    Example:
        >>> game_analysis("8f2a9c")
        'analysis/8f2a9c.json'
    """
    return f"analysis/{game_id}.json"


def game_training_data(game_id: str) -> str:
    """
    Generate key for game training data (future use).

    This is a placeholder for when we add training features.

    Args:
        game_id: Unique game identifier

    Returns:
        R2 object key (e.g., "training/abc123.json")

    Example:
        >>> game_training_data("8f2a9c")
        'training/8f2a9c.json'
    """
    return f"training/{game_id}.json"


def game_thumbnail(game_id: str) -> str:
    """
    Generate key for game board thumbnail (future use).

    This is a placeholder for when we add board snapshots.

    Args:
        game_id: Unique game identifier

    Returns:
        R2 object key (e.g., "thumbnails/abc123.png")

    Example:
        >>> game_thumbnail("8f2a9c")
        'thumbnails/8f2a9c.png'
    """
    return f"thumbnails/{game_id}.png"


# Key pattern documentation for future reference
KEY_PATTERNS = {
    "game_pgn": "games/{game_id}.pgn",
    "game_analysis": "analysis/{game_id}.json",
    "game_training": "training/{game_id}.json",
    "game_thumbnail": "thumbnails/{game_id}.png",
}
